# Generated by Django 3.1.3 on 2020-11-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='project',
        ),
    ]
