# Generated by Django 3.1.3 on 2020-11-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_hazard_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
    ]
