# Generated by Django 3.1.3 on 2020-11-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201128_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazard',
            options={'ordering': ['risk_level'], 'verbose_name_plural': 'Hazards'},
        ),
        migrations.AddField(
            model_name='hazard',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
    ]
