# Generated by Django 3.1.3 on 2020-11-29 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0005_auto_20201129_0102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('number', 'POR')},
        ),
    ]
