# Generated by Django 3.1.3 on 2020-11-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201129_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['number', 'POR'], 'verbose_name_plural': 'Projects'},
        ),
    ]
