# Generated by Django 3.1.3 on 2020-11-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201129_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['POR', 'number'], 'verbose_name_plural': 'Projects'},
        ),
    ]
