# Generated by Django 3.1.3 on 2020-12-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20201130_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='residual',
        ),
        migrations.AddField(
            model_name='hazard',
            name='res_risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_risk_level', to='todo.risklevel'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.person'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_level', to='todo.risklevel'),
        ),
    ]
