# Generated by Django 3.1.3 on 2020-12-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20201203_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_member',
        ),
        migrations.AddField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
    ]
