# Generated by Django 3.1.3 on 2020-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20201203_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.AddField(
            model_name='person',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_stakeholder',
            field=models.BooleanField(default=False),
        ),
    ]
