# Generated by Django 3.1.3 on 2020-12-04 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20201203_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='members',
            new_name='rep',
        ),
        migrations.RemoveField(
            model_name='person',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_stakeholder',
        ),
        migrations.RemoveField(
            model_name='person',
            name='project',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.person'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
    ]
