# Generated by Django 3.1.4 on 2020-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20201204_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
