# Generated by Django 3.1.4 on 2020-12-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20201204_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_stakeholder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
    ]
