# Generated by Django 3.1.4 on 2020-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20201204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_stakeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_team_member',
            field=models.BooleanField(default=True),
        ),
    ]
