# Generated by Django 3.1.4 on 2020-12-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20201204_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='department',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
