# Generated by Django 3.1.4 on 2020-12-05 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20201204_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='res_risk_level',
        ),
    ]
