# Generated by Django 3.1.4 on 2020-12-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_remove_hazard_res_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='res_risk_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_risk_level', to='todo.risklevel'),
        ),
    ]
