# Generated by Django 3.1.4 on 2020-12-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_historicalcontrolmeasure_historicalhazard_historicalperson_historicalproject_historicalrisklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcontrolmeasure',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalhazard',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalrisklevel',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
