# Generated by Django 3.1.4 on 2020-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20201215_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='EGBC_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='PPM_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='SAP_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='SBD_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='SPOT_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='EGBC_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='PPM_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SAP_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SBD_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SPOT_link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
    ]
