# Generated by Django 3.1.4 on 2020-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20201215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='EGBC_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Engineering\\Distribution\0 EGBC Filing\1 General DRE', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='SBD_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Engineering\\Distribution\0 EGBC Filing\1 General DRE', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='SPOT_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Field Ops\\SAM\\Distribution Planning\\System Improvement\\SPOT Project Documentation', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='EGBC_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Engineering\\Distribution\EGBC Filing\1 General DRE', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='SBD_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Engineering\\Distribution\0 EGBC Filing\1 General DRE', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='SPOT_link',
            field=models.CharField(default=r'\\bchydro.adroot.bchydro.bc.ca\\data\\Field Ops\\SAM\\Distribution Planning\\System Improvement\\SPOT Project Documentation', max_length=240),
        ),
    ]
