# Generated by Django 3.1.4 on 2020-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_auto_20201216_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='EGBC_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='SBD_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='SPOT_link',
            field=models.CharField(default='\\\\bchydro.adroot.bchydro.bc.ca\\data\\Field Ops\\SAM\\Distribution Planning\\System Improvement\\SPOT Project Documentation', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='EGBC_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='SBD_link',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='project',
            name='SPOT_link',
            field=models.CharField(default='\\\\bchydro.adroot.bchydro.bc.ca\\data\\Field Ops\\SAM\\Distribution Planning\\System Improvement\\SPOT Project Documentation', max_length=240),
        ),
    ]
