# Generated by Django 3.1.4 on 2020-12-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_auto_20201223_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
