# Generated by Django 3.1.4 on 2020-12-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_auto_20201224_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='SPOT_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='SPOT_link',
        ),
    ]
