# Generated by Django 3.1.4 on 2020-12-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_auto_20201229_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='EGBC_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='EGBC_link',
        ),
    ]
