# Generated by Django 3.1.4 on 2021-01-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0033_auto_20201229_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='PPM_link',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='SBD_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='PPM_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='SBD_link',
        ),
    ]
