# Generated by Django 3.1.4 on 2021-01-03 03:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0034_auto_20210102_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='hazard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_team_member': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='todo.person'),
        ),
        migrations.AlterField(
            model_name='historicalhazard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_team_member': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.person'),
        ),
        migrations.CreateModel(
            name='engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.hazard')),
                ('persons', models.ManyToManyField(to='todo.Person')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
