# Generated by Django 3.1.4 on 2021-01-03 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_auto_20210103_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='hazard',
        ),
        migrations.AddField(
            model_name='engagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.project'),
        ),
    ]
