# Generated by Django 3.1.4 on 2021-01-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_auto_20210103_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='persons',
        ),
        migrations.AddField(
            model_name='engagement',
            name='stakeholders',
            field=models.ManyToManyField(limit_choices_to={'is_stakeholder': True}, to='todo.Person'),
        ),
    ]
