# Generated by Django 3.1.4 on 2021-01-05 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0037_auto_20210103_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='stakeholders',
            field=models.ManyToManyField(to='todo.Person'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_assigned_to', to='todo.person'),
        ),
        migrations.AlterField(
            model_name='historicalhazard',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.person'),
        ),
    ]
