# Generated by Django 3.1.4 on 2021-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0038_auto_20210105_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='stakeholders',
            field=models.ManyToManyField(db_table='todo_engagement_stakeholders', to='todo.Person'),
        ),
    ]
