# Generated by Django 3.1.4 on 2021-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0039_auto_20210105_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='stakeholder_string',
            field=models.TextField(blank=True),
        ),
    ]
