# Generated by Django 3.1.4 on 2021-01-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0040_engagement_stakeholder_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='stakeholder_string',
            new_name='stakeholders_string',
        ),
    ]
