# Generated by Django 3.1.5 on 2021-01-11 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0042_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VI', [('Victoria & Saanich', 'Victoria & Saanich'), ('Western Communities', 'Western Communities'), ('Duncan & Gulf Islands', 'Duncan & Gulf Islands'), ('Central VI', 'Central VI'), ('Northern VI', 'Northern VI')]), ('Interior & NIA', [('Northern Interior', 'Northern Interior'), ('Southern Interior', 'Southern Interior')]), ('LMN', [('Vancouver', 'Vancouver'), ('Burnaby', 'Burnaby'), ('North Shore', 'North Shore')]), ('LMS', [('Fraser Valley West', 'Fraser Valley West'), ('Fraser Valley East', 'Fraser Valley East')])], max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_team_member',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='todo.region')),
            ],
        ),
    ]
