# Generated by Django 3.1.5 on 2021-01-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0043_auto_20210111_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.location'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='todo.region'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('VI', [('Victoria & Saanich', 'Victoria & Saanich'), ('Western Communities', 'Western Communities'), ('Duncan & Gulf Islands', 'Duncan & Gulf Islands'), ('Central VI', 'Central VI'), ('Northern VI', 'Northern VI')]), ('Interior & NIA', [('Northern Interior', 'Northern Interior'), ('Southern Interior', 'Southern Interior')]), ('LMN', [('Vancouver', 'Vancouver'), ('Burnaby', 'Burnaby'), ('North Shore', 'North Shore')]), ('LMS', [('Fraser Valley West', 'Fraser Valley West'), ('Fraser Valley East', 'Fraser Valley East')])], max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.region'),
        ),
    ]
