# Generated by Django 3.1.5 on 2021-01-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0044_auto_20210111_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
    ]
