# Generated by Django 3.1.5 on 2021-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0046_auto_20210111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('VI', 'VI'), ('Interior & NIA', 'Interior & NIA'), ('LMN', 'LMN'), ('LMS', 'LMS')], max_length=60),
        ),
    ]
