# Generated by Django 3.1.5 on 2021-01-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0047_auto_20210111_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicalrisklevel',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalControlMeasure',
        ),
        migrations.DeleteModel(
            name='HistoricalPerson',
        ),
        migrations.DeleteModel(
            name='HistoricalRiskLevel',
        ),
    ]
