# Generated by Django 3.1.5 on 2021-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0048_auto_20210113_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AddField(
            model_name='hazard',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhazard',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
