# Generated by Django 3.1.5 on 2021-01-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0050_auto_20210114_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazard',
            name='number',
        ),
        migrations.RemoveField(
            model_name='historicalhazard',
            name='number',
        ),
    ]
