# Generated by Django 3.1.5 on 2021-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0051_auto_20210114_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazard',
            options={'verbose_name_plural': 'hazards'},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('project', 'first_name', 'last_name')},
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together={('project', 'first_name', 'last_name')},
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(fields=['description'], name='hazard_idx'),
        ),
    ]
