# Generated by Django 3.1.5 on 2021-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0052_auto_20210114_1333'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hazard',
            name='hazard_idx',
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(db_tablespace='indexes', fields=['description', 'project'], name='hazard_idx'),
        ),
    ]
