# Generated by Django 3.1.5 on 2021-01-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0053_auto_20210114_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhazard',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
