# Generated by Django 3.1.5 on 2021-01-27 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0054_auto_20210114_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'regions'},
        ),
        migrations.RemoveIndex(
            model_name='hazard',
            name='hazard_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='POR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.region'),
        ),
        migrations.AlterUniqueTogether(
            name='hazard',
            unique_together={('index', 'project')},
        ),
    ]
