# Generated by Django 3.1.5 on 2021-02-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0057_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='EGBC_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='EGBC_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='SBD_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SBD_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),        migrations.AddField(
            model_name='historicalproject',
            name='SPOT_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='SPOT_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),        migrations.AddField(
            model_name='historicalproject',
            name='PPM_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='PPM_link',
            field=models.CharField(blank=True, default='\\\\bchydro.adroot.bchydro.bc.ca/data/Engineering/Distribution/0 EGBC Filing/4 Projects', max_length=240, null=True),
        ),
    ]
