# Generated by Django 3.1.5 on 2021-03-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0059_auto_20210223_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(choices=[('Definition', 'Definition'), ('Design', 'Design'), ('Construction', 'Construction'), ('Close Out', 'Close Out')], max_length=60),
        ),
    ]
