# Generated by Django 3.1.5 on 2021-03-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0061_auto_20210308_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazard',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhazard',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
