# Generated by Django 3.1.5 on 2021-03-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0062_auto_20210312_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='recommendations',
            field=models.CharField(blank=True, choices=[], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhazard',
            name='recommendations',
            field=models.CharField(blank=True, choices=[], max_length=240, null=True),
        ),
    ]
