# Generated by Django 3.1.5 on 2021-03-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0063_auto_20210312_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='recommendations',
            field=models.CharField(blank=True, choices=[], max_length=480, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhazard',
            name='recommendations',
            field=models.CharField(blank=True, choices=[], max_length=480, null=True),
        ),
    ]
